"""
Dataset verification service.

This module implements the Verification Service responsible for assessing
the quality of a recovered dataset after schema recovery has completed.

The Verification Service evaluates the recovered DataFrame together
with the schema recovery results to verify that the recovered dataset
accurately represents the expected recovery outcome.

Responsibilities:
- Verify all expected recovered columns are present.
- Report unresolved schema mappings.
- Detect duplicate canonical columns.
- Determine the overall verification severity.
- Produce a VerificationResult.

This module intentionally does not:
- Perform schema recovery.
- Modify recovered DataFrames.
- Format DataFrames.
- Generate healing reports.
- Export CSV files.
- Build API response models.
"""

# IMPORTS
import pandas as pd

from backend.models.schema_mapping_models import (
    MappingStatus,
    SchemaMapping,
)
from backend.models.verification_models import (
    VerificationFinding,
    VerificationResult,
    VerificationSeverity,
    VerificationType,
)

# VERIFICATION SERVICE
class VerificationService:
    """
    Service responsible for verifying the quality of a recovered dataset.

    The Verification Service evaluates the recovered DataFrame together
    with schema recovery results against the canonical CRM schema and
    produces structured verification findings for downstream consumers.
    """

    def verify(
        self,
        recovered_dataframe: pd.DataFrame,
        mappings: list[SchemaMapping]
    ) -> VerificationResult:
        """
        Verify that the recovered dataset accurately represents the schema
        recovery outcome.

        Parameters:

        recovered_dataframe:
            The recovered dataset produced after schema recovery.

        mappings:
            Schema mappings produced by the recovery pipeline.

        Returns:

        VerificationResult:
            The complete dataset verification outcome.
        """

        # Collect all verification findings produced by the verification rules.
        findings: list[VerificationFinding] = []

        # Execute dataset verification rules.
        findings.extend(
            self._check_missing_expected_columns(
                recovered_dataframe=recovered_dataframe,
                mappings=mappings
            )
        )

        findings.extend(
            self._check_unresolved_columns(
                mappings=mappings
            )
        )

        findings.extend(
            self._check_duplicate_columns(
                recovered_dataframe=recovered_dataframe
            )
        )

        # Summarize the overall verification outcome.
        overall_severity = self._determine_overall_severity(findings)

        is_dataset_verified = (
            self._determine_dataset_verification_status(
                overall_severity=overall_severity,
            )
        )

        # Return an immutable snapshot of the verification results.
        return VerificationResult(
            is_dataset_verified=is_dataset_verified,
            overall_severity=overall_severity,
            findings=tuple(findings),
        )


    # CHECK FOR MISSING EXPECTED COLUMNS
    def _check_missing_expected_columns(
        self,
        recovered_dataframe: pd.DataFrame,
        mappings: list[SchemaMapping],
    ) -> list[VerificationFinding]:
        """
        Check whether the recovered dataset contains all expected
        recovered columns produced by the recovery pipeline.

        Parameters:

        recovered_dataframe:
            The recovered dataset produced after schema recovery.

        mappings:
            Schema mappings produced by the recovery pipeline.

        Returns:

        list[VerificationFinding]:
            Verification findings describing any missing required columns.
        """

        # Collect verification findings generated by this rule.
        findings: list[VerificationFinding] = []

        # Create a set for efficient membership lookups.
        recovered_columns = set(recovered_dataframe.columns)

        # Derive the expected recovered schema from resolved mappings.
        expected_recovered_columns = {
            mapping.canonical_field
            for mapping in mappings
            if (
                mapping.status == MappingStatus.RESOLVED
                and mapping.canonical_field is not None
            )
        }

        # Identify expected recovered columns missing from the recovered dataset.
        missing_columns = sorted(
            expected_recovered_columns - recovered_columns
        )

        # Return immediately when no required columns are missing.
        if not missing_columns:
            return findings

        # Record the missing required columns as a verification finding.
        findings.append(
            VerificationFinding(
                severity=VerificationSeverity.ERROR,
                type=VerificationType.MISSING_REQUIRED_COLUMNS,
                affected_columns=missing_columns,
                message=(
                    "The recovered dataset is missing one or more required "
                    "canonical columns."
                ),
            )
        )

        return findings


    # CHECK FOR UNRESOLVED COLUMNS
    def _check_unresolved_columns(
        self,
        mappings: list[SchemaMapping],
    ) -> list[VerificationFinding]:
        """
        Check whether any uploaded columns remain unresolved after schema
        recovery.

        Parameters:

        mappings:
            Schema mappings produced by the recovery pipeline.

        Returns:

        list[VerificationFinding]:
            Verification findings describing unresolved schema mappings.
        """

        # Collect verification findings generated by this rule.
        findings: list[VerificationFinding] = []

        # Identify uploaded headers that remain unresolved.
        unresolved_columns = [
            mapping.source_header
            for mapping in mappings
            if mapping.status == MappingStatus.PENDING
        ]

        # Return immediately when all uploaded columns were resolved.
        if not unresolved_columns:
            return findings

        # Record unresolved schema mappings as a verification finding.
        findings.append(
            VerificationFinding(
                severity=VerificationSeverity.ERROR,
                type=VerificationType.UNRESOLVED_COLUMNS,
                affected_columns=unresolved_columns,
                message=(
                    "One or more uploaded columns could not be matched automatically "
                    "and require manual mapping."
                ),
            )
        )

        return findings

    # CHECK FOR DUPLICATE COLUMNS
    def _check_duplicate_columns(
        self,
        recovered_dataframe: pd.DataFrame,
    ) -> list[VerificationFinding]:
        """
        Check whether the recovered dataset contains duplicate column names.

        Parameters:

        recovered_dataframe:
            The recovered dataset produced after schema recovery.

        Returns:

        list[VerificationFinding]:
            Verification findings describing duplicate dataset columns.
        """

        # Collect verification findings generated by this rule.
        findings: list[VerificationFinding] = []

        # Identify duplicate column names while reporting each duplicate only once.
        duplicate_columns = (
            recovered_dataframe.columns[
                recovered_dataframe.columns.duplicated()
            ]
            .unique()
            .tolist()
        )

        # Return immediately when no duplicate columns exist.
        if not duplicate_columns:
            return findings

        # Record duplicate canonical columns as a verification finding.
        findings.append(
            VerificationFinding(
                severity=VerificationSeverity.ERROR,
                type=VerificationType.DUPLICATE_COLUMNS,
                affected_columns=duplicate_columns,
                message=(
                    "The recovered dataset contains duplicate canonical "
                    "column names."
                ),
            )
        )

        return findings

    # CHECKS FOR SEVERITY LEVELS
    def _determine_overall_severity(
        self,
        findings: list[VerificationFinding],
    ) -> VerificationSeverity:
        """
        Determine the highest verification severity across all findings.

        Parameters:

        findings:
            Verification findings produced during dataset verification.

        Returns:

        VerificationSeverity:
            The highest severity identified across all verification findings.
        """

        # A dataset with no findings is considered informational.
        if not findings:
            return VerificationSeverity.INFO

        # Return the highest severity across all findings.
        return max(
            finding.severity
            for finding in findings
        )

    # VERIFIES THE RECOVERED DATA
    def _determine_dataset_verification_status(
        self,
        overall_severity: VerificationSeverity,
    ) -> bool:
        """
        Determine whether the recovered dataset satisfies verification
        requirements.

        Parameters:

        overall_severity:
            The highest verification severity identified across all
            verification findings.

        Returns:

        bool:
            True when the dataset passes verification, otherwise False.
        """

        return overall_severity != VerificationSeverity.ERROR
    

    
    