# Import libraries:

# Delays evaluation of type hints until runtime.
# Helps prevent circular import issues in larger projects.
from __future__ import annotations
# Generates boilerplate methods like __init__, __repr__, and __eq__.
from dataclasses import dataclass
# Deals with all kinds of datatypes
from typing import Any

"""
Infrastructure models for LLM communication.

These models define the provider-agnostic request and response
contracts used between the business layer and the LLM infrastructure.
"""

# frozen=True makes the object immutable after creation. Request should never change once they are built.
@dataclass(frozen=True)
class LLMRequest:
    """
    Represents a request sent to an LLM.
    """
    system_prompt: str                          # Defines AI's permanent behavior/instructions.
    user_prompt: str                            # Contains actual task or user-specific input.
    prompt_version: str                         # Tracks which prompt template generated this request.


# Represents the final result returned by the LLM infrastructure.
# Contains both the generated output and useful operational metadata.
@dataclass(frozen=True)
class LLMResponse:
    """
    Represents a successful response returned by an LLM.
    """

    # Parse JSON returned by the provider.
    # The business layer consumes this instead of raw provider objects.
    structured_output: dict[str, Any]

    # Model that generated the response.
    model_name: str

    # Prompt template version used for this request.
    prompt_version: str

    # Total response time in milliseconds.
    latency_ms: float

    # Tokens consumed by the input prompt.
    input_tokens: int

    # Tokens generated by the model.
    output_tokens: int

    # Total tokens used for billing and monitoring.
    total_tokens: int

    # Indicates why the model stopped generating.
    finish_reason: str